// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcY-ykP2wM2KLcMVYOaNFtw0LwYlMizgg',
    appId: '1:395189570896:web:393f7b0979f8447f70b055',
    messagingSenderId: '395189570896',
    projectId: 'kos-app-7b60b',
    authDomain: 'kos-app-7b60b.firebaseapp.com',
    storageBucket: 'kos-app-7b60b.appspot.com',
    measurementId: 'G-0790ND6X7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFnoNjB5hOIjxUJS0XFk9jXhR0TVp792k',
    appId: '1:395189570896:android:369dfb7ecc77599770b055',
    messagingSenderId: '395189570896',
    projectId: 'kos-app-7b60b',
    storageBucket: 'kos-app-7b60b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB95SZ0yZUFepOPEhuGF73dqFbPTnizNWo',
    appId: '1:395189570896:ios:28c7998b50a9308370b055',
    messagingSenderId: '395189570896',
    projectId: 'kos-app-7b60b',
    storageBucket: 'kos-app-7b60b.appspot.com',
    iosBundleId: 'com.example.kosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB95SZ0yZUFepOPEhuGF73dqFbPTnizNWo',
    appId: '1:395189570896:ios:56a694186a1e08a170b055',
    messagingSenderId: '395189570896',
    projectId: 'kos-app-7b60b',
    storageBucket: 'kos-app-7b60b.appspot.com',
    iosBundleId: 'com.example.kosApp.RunnerTests',
  );
}
